use_frameworks!

platform :ios, '8.0'

target 'CMPushNotificationService_Example' do
  pod 'CMPushNotificationService', :path => '../'

  target 'CMPushNotificationService_Tests' do
    inherit! :search_paths

    
  end
end
